# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-13 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('body', django_markdown.models.MarkdownField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
